# Generated by Django 4.2.6 on 2024-10-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_book_cover_role_review_book_cover_alter_profile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(to="myapp.genre"),
        ),
    ]
