# Generated by Django 4.2.6 on 2024-10-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_genre_book_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cover",
            name="file_name",
        ),
        migrations.AddField(
            model_name="cover",
            name="cover",
            field=models.ImageField(
                default="book_covers/base.jpg", upload_to="book_covers/"
            ),
        ),
    ]
