# Generated by Django 4.2.6 on 2024-10-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_cover_file_name_cover_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="greenhouse",
            name="user",
        ),
        migrations.RemoveField(
            model_name="historicalingreenhouse",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalingreenhouse",
            name="plant",
        ),
        migrations.RemoveField(
            model_name="historicalingreenhouse",
            name="user",
        ),
        migrations.RemoveField(
            model_name="historicalplant",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="ingreenhouse",
            name="plant",
        ),
        migrations.RemoveField(
            model_name="ingreenhouse",
            name="user",
        ),
        migrations.RemoveField(
            model_name="plantcare",
            name="plant",
        ),
        migrations.RemoveField(
            model_name="planttype",
            name="plant_type",
        ),
        migrations.RemoveField(
            model_name="temperature",
            name="user",
        ),
        migrations.DeleteModel(
            name="Compatibility",
        ),
        migrations.DeleteModel(
            name="Greenhouse",
        ),
        migrations.DeleteModel(
            name="HistoricalInGreenhouse",
        ),
        migrations.DeleteModel(
            name="HistoricalPlant",
        ),
        migrations.DeleteModel(
            name="InGreenhouse",
        ),
        migrations.DeleteModel(
            name="Plant",
        ),
        migrations.DeleteModel(
            name="PlantCare",
        ),
        migrations.DeleteModel(
            name="PlantType",
        ),
        migrations.DeleteModel(
            name="Temperature",
        ),
    ]
